# Generated by Django 3.2.9 on 2022-02-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearninguser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='elearninguser',
            name='spouse_name',
        ),
    ]
