# Generated by Django 3.2.9 on 2022-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_auto_20220210_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearninguser',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='index_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='street_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher'), ('ADMIN', 'admin')], default='STUDENT', max_length=7),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='elearninguser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
